# top level stuff you probably don't need to touch
collections:
  projects:
    output: true
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      color: rgb(251, 151, 45)

# edit here to achieve your personal greatness
url: http://foolmoron.io/
baseurl: /
title: Momin Khan
author: Momin Khan
description: Personal site and resume
avatar: profile.png
email: foolmoron@gmail.com
github: foolmoron
twitter: foolmoron
linkedin: momink
disqus: foolmoron
google_analytics: UA-48768978-1