# top level stuff you probably don't need to touch
collections:
  projects:
    output: true
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
port: 3000
safe: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      color: rgb(251, 151, 45)

# not sure where else to put this...
friends:
-
  name: "Test 1"
  url: "www.google.com"
  description: "Test is a pretty cool guy."
-
  name: "Mike Odum"
  url: "www.google.com"
  description: "The ROOT 76 art director and freelance illustrator extraordinaire!"

# edit here to achieve your personal greatness
url: http://foolmoron.io/
baseurl: /
title: Momin Khan
author: Momin Khan
description: Momin Khan's personal site for web and game development and such
email: foolmoron@gmail.com
github: foolmoron
twitter: foolmoron
steam: foolmoron
linkedin: momink
disqus: foolmoron
google_analytics: UA-48768978-1